In [4]:
import io
import pandas as pd
csv_data="""age,name,gender,income
10,a,g,46000
20,f,f,78000
26,h,,89000
"""
df=pd.read_csv(io.StringIO(csv_data))
print(df)
print(df.shape)
print(df.columns.tolist())
print(df.index.tolist())
print(df.dtypes)
df[["age","name"]]
slice_df=df.iloc[1:2,0:2]
slice_df
print(slice_df)
row_record=df.loc[0:1,"age":"gender"]
row_record
df["income"]>50000.0
df["age"]>12.0
df.groupby("gender")["income"].mean()
df.isnull().sum()

   age name gender  income
0   10    a      g   46000
1   20    f      f   78000
2   26    h    NaN   89000
(3, 4)
['age', 'name', 'gender', 'income']
[0, 1, 2]
age       int64
name        str
gender      str
income    int64
dtype: object
   age name
1   20    f

age       0
name      0
gender    1
income    0
dtype: int64

In [34]:
df.info
print(df)

   age name gender  income
0   10    a    NaN   46000
1   20    f      f   78000
2   26    h    NaN   89000

In [3]:
df["age"]>20

0    False
1    False
2     True
Name: age, dtype: bool

In [4]:
df.dtypes

age       int64
name        str
gender      str
income    int64
dtype: object

In [5]:
df["income"].astype("float64")

0    46000.0
1    78000.0
2    89000.0
Name: income, dtype: float64

In [6]:
slice_df=df.iloc[1:4,0:4]
slice_df

   age name gender  income
1   20    f      f   78000
2   26    h      m   89000

In [7]:
df[(df["income"]>40000)&(df["gender"]=="f")]

   age name gender  income
1   20    f      f   78000

In [8]:
df[(df["income"]>40000)|(df["gender"]=="f")]

   age name gender  income
0   10    a      m   46000
1   20    f      f   78000
2   26    h      m   89000

In [9]:
import pandas as pd
print(csv_data)

age,name,gender,income
10,a,m,46000
20,f,f,78000
26,h,m,89000

In [10]:
df.dtypes

age       int64
name        str
gender      str
income    int64
dtype: object

In [29]:
df=df.dropna
print(df)

<bound method DataFrame.dropna of    age name gender  income
0   10    a    NaN   46000
1   20    f      f   78000
2   26    h    NaN   89000>

In [5]:
df.groupby("gender")["income"].mean()

gender
f    78000.0
g    46000.0
Name: income, dtype: float64

In [6]:
mean=df["age"].mean()
df ["age"]=df["age"].fillna(mean)
print (mean)

18.666666666666668

In [10]:
df.groupby("gender")[["income","age"]].mean()

         income   age
gender
f       78000.0  20.0
g       46000.0  10.0

In [9]:
df.isnull().sum()

age       0
name      0
gender    1
income    0
dtype: int64